apiVersion: v2
name: apiclarity
appVersion: 1.0.0
description: Charts for APIClarity deployment. Reconstruct OpenAPI Specifications from real-time workload traffic seamlessly.
version: 1.0.0
home: https://apiclarity.io/
icon: https://github.com/openclarity/apiclarity/raw/master/API_clarity.svg
sources:
  - https://github.com/openclarity/apiclarity
maintainers:
  - name: API Clarity
    url: https://apiclarity.io
type: application
dependencies:
  - name: postgresql
    version: "11.6.7"
    repository: https://charts.bitnami.com/bitnami
    condition: postgresql.enabled
