apiVersion: v2
name: apiclarity
appVersion: devel-global-specs
description: Charts for APIClarity deployment. Reconstruct OpenAPI Specifications from real-time workload traffic seamlessly.
version: 0.0
home: https://apiclarity.io/
icon: https://github.com/openclarity/apiclarity/raw/master/API_clarity.svg
sources:
  - https://github.com/openclarity/apiclarity
maintainers:
  - name: API Clarity
    url: https://apiclarity.io
type: application
dependencies:
  - name: postgresql
    version: "11.6.12"
    repository: https://charts.bitnami.com/bitnami
    condition: apiclarity-postgresql.enabled
    alias: apiclarity-postgresql
