openapi: 3.0.3
info:
  title: APIClarity Analytics Core
  version: 0.0.1
  description: APIClarity Analytics Core Module API
paths:
  /version:
    get:
      operationId: getVersion
      summary: Get the version of this Module
      description: Get the version of this Module
      responses:
        '200':
          description: Version of the Module
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Version'

components:
  schemas:
    Version:
      type: 'object'
      required: [version]
      properties:
        version:
          type: 'string'