info: 
  title: "Core OAPI for APIClarity Notification"
  version: "1.0"
openapi: 3.0.2
servers:
  - url: /
paths:
  /notification/{apiID}:
    post:
      summary: 'Provide to Apiclarity list of raw input for a given API ID associated with a given timestamp'
      parameters:
        - name: apiID
          in: path
          required: true
          schema:
            type: integer
            format: int64
      requestBody:
        description: 'Notification'
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/APIClarityNotification'
      responses:
        '200':
          description: 'Success'
          content:
            application/json:
              schema:
                type: string

components:
  schemas:
    APIClarityNotification:
      oneOf: []
      discriminator:
        propertyName: notificationType
        mapping: {}