{{- if .Values.trafficSource.apigee.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "apiclarity.name" . }}-lb-service
  namespace: '{{ .Release.Namespace }}'
  labels:
    {{ include "apiclarity.labels" . }}
  annotations:
    helm.sh/hook: pre-install
spec:
  ports:
    - name: trace-server
      port: 9000
      protocol: TCP
      targetPort: 9000
  selector:
    app: {{ include "apiclarity.name" . }}
  sessionAffinity: None
  type: LoadBalancer
{{- end }}