apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "apiclarity.name" . }}
  labels:
    {{ include "apiclarity.labels" . }}
rules:
  - apiGroups: [ "" ]
    resources: [ "pods" ]
    verbs: [ "list", "get", "watch" ]
  - apiGroups: [ "apps" ]
    resources: [ "deployments" ]
    verbs: [ "list", "get", "watch" ]
  - apiGroups: [ "apps" ]
    resources: [ "replicasets" ]
    verbs: [ "list", "get", "watch" ]
  - apiGroups: [ "apps" ]
    resources: [ "daemonsets" ]
    verbs: [ "list", "get", "watch" ]
  - apiGroups: [""]
    resources: ["nodes", "services"]
    verbs: ["get", "list", "watch"]
