{{- if .Values.apiclarity.rbac.create -}}
{{- if .Values.global.traceSampling.enable -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "apiclarity.name" . }}
  namespace: '{{ .Release.Namespace }}'
  labels:
    {{ include "apiclarity.labels" . }}
rules:
  # needed for trace sampling manger
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get", "create", "update", "delete"]
{{- end -}}
{{- end -}}
