name: Release

on:
  workflow_dispatch: {}

env:
  GO_VERSION: 1.17
  OTEL_COLLECTOR_VERSION: 0.60.0

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: ${{ env.GO_VERSION }}

    - shell: bash
      run: |
        sudo apt-get install libpcap-dev

    - name: Check out code
      uses: actions/checkout@v3

    - name: Run verification
      run: make check

    - name: Build Docker image
      run: make push-docker
